apiVersion: v1
kind: Secret
metadata: 
    name: dbsecret
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
    MYSQL_USER: dXNlcg==
    MYSQL_PASSWORD: MTIzNA==
    MLYSQL_HOST: bXlzcWw=
    MYSQL_PORT: MzMwNg==
    MYSQ_DATABASE: ZXhhbXBsZQ==