frontend:
  name: frontend
  replicas: 2
  labels:
    app: frontend
  image:
    name: 644435390668.dkr.ecr.eu-west-1.amazonaws.com/matan-task-scrape-portfolio
    tagName: frontend
    imagePullPolicy: Always
    resources: {}
    containerPort: 80
    secretEnvName: ""
  service:
    name: frontend
    port: 80
    type: ClusterIP

backend:
  name: backend
  replicas: 2
  labels:
    app: backend
  image:
    name: 644435390668.dkr.ecr.eu-west-1.amazonaws.com/matan-task-scrape-portfolio
    tagName: backend
    imagePullPolicy: Always
    resources: {}
    containerPort: 5000
    secretEnvName: "dbsecret"
  service:
    name: server
    port: 5000
    type: ClusterIP