{{- $chartName := .Chart.Name -}}
{{- $appVersion := .Chart.AppVersion -}}
{{- with .Values.database }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $chartName }}-{{ .name }}
spec:
  selector:
    matchLabels:
      {{- toYaml .labels | nindent 6 }}
  serviceName: "mysql"
  replicas: {{ .replicas }}
  template:
    metadata:
      labels:
        {{- toYaml .labels | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      {{- with .image }}
      - name: {{ $chartName }}-{{ .name }}
        image: {{ .name }}
        ports:
        - containerPort: {{ .containerPort }}
        # volumeMounts:
        # - name: mysql-store
        #   mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .secretEnvName }}
                key: MYSQL_ROOT_PASSWORD
      {{- end }}
      
  volumeClaimTemplates:
  - metadata:
      name: mysql-db
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ""
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $chartName }}-{{ .name }}
spec:
  selector:
    {{- toYaml .labels | nindent 4 }}
  ports:
    - name: {{ .service.name }}
      port: {{ .service.port }}
  type: {{ .service.type }}
{{- end }}
