{{- $chartName := .Chart.Name -}}
{{- $appVersion := .Chart.AppVersion -}}
{{- with .Values.frontend }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $chartName }}-{{ .name }}
spec:
  selector:
    matchLabels:
      {{- toYaml .labels | nindent 6 }}
  replicas: {{ .replicas }}
  template:
    metadata:
      labels:
        {{- toYaml .labels | nindent 8 }}
    spec:
      containers:
      - name: {{ $chartName }}-{{ .name }}
        {{- with .image }}
        image: nginx:latest
        imagePullPolicy:  {{ .imagePullPolicy }}
        {{- if .resources }}
        resources:
          {{- toYaml .resources | nindent 10 }}
        {{- end }}

        volumeMounts:
          - name: nginx-configmap
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true

      volumes:
      - configMap:
          name: conf-nginx
          items:
            - key: nginx.conf
              path: nginx.conf
        name: nginx-configmap
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
spec:
  selector:
    {{- toYaml .labels | nindent 4 }}
  ports:
    - name: {{ .service.name }}
      port: {{ .service.port }}
  type: {{ .service.type }}
{{- end }}
