apiVersion: v1
kind: Secret
metadata: 
    name: dbsecret
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
    MYSQL_USER: dXNlcg==
    MYSQL_PASSWORD: MTIzNA==
    MYSQL_HOST: bXlzcWwtaGVhZGxlc3M=
    MYSQL_PORT: MzMwNg==
    MYSQL_DATABASE: ZXhhbXBsZQ==